### ISSUE TITLE
Error in MASM code for right shift

### ISSUE THREAD

**Issue by RichardAth** [JesperMikkelsen/Big-Numbers#2]
At line 462 I changed eax to rax.
Line is now
shrd        qword ptr[rax], rdx, cl        ; shift x.lo taking new bits from x.hi (rdx)

Curiously, the old version sometimes worked and sometimes errored, but the new version appears to be 100% reliable.

PS Re issue reported above: the filename is Int128x64.asm, and the line number is 456, not 462

**Comment by RichardAth** [comment]
Re issue reported above: the filename is Int128x64.asm, and the line number is 456, not 462

**Comment by JesperMikkelsen** [comment]
Thanks.  It's odd, that masm doesn't report an error on this line
